version: "3.9"

services:
  mongo_db:
    container_name: db_mongo
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  api1:
    build: .
    #hostname: api01
    ports:
      - 4000:3000
    environment:
      MONGO_URI: mongodb://db_mongo:27017/
      PORT: 3000
    depends_on:
      - mongo_db

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - api1

volumes:
  mongo_db: {}
